# Lab 1: CIFAR10 Challenge

**CIFAR10** (http://www.cs.toronto.edu/~kriz/cifar.html) is one of the most famous ML data sets. 

## Data
* 32x32 color images
* in 10 classes
* 50k training images
* 10k test images



<img src="https://production-media.paperswithcode.com/datasets/CIFAR-10-0000000431-b71f61c0_U5n3Glr.jpg" width=700>

In [68]:
#get data
from keras.datasets import cifar10
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

In [69]:
#traindata: 50k 32X32 rgb images
X_train.shape

(50000, 32, 32, 3)

In [70]:
#labels
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

## Task: build the best classifier (with feature extration) using the methods you know from ML1+2
* work in small teams (2-4)
* use NumPy pre-processing, feature extraction and hyer-parameter tuning in Scikit-Learn
* no Neural Networks! 
* best test F1-Score after 90min winns! 

In [71]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import f1_score

In [72]:
Xnew = X_train.reshape(50000,32*32*3)
Xnew

array([[ 59,  62,  63, ..., 123,  92,  72],
       [154, 177, 187, ..., 143, 133, 144],
       [255, 255, 255, ...,  80,  86,  84],
       ...,
       [ 35, 178, 235, ...,  12,  31,  50],
       [189, 211, 240, ..., 195, 190, 171],
       [229, 229, 239, ..., 163, 163, 161]], dtype=uint8)

In [ ]:
clf = GradientBoostingClassifier()
clf.fit(Xnew, y_train)
y_pred = clf.predict(X_test.reshape(10000,32*32*3))
f1_score(y_test, y_pred, average=None)

#bei allen
#array([0.55616032, 0.53646598, 0.34526991, 0.31969027, 0.39822573,
#       0.41167435, 0.51486054, 0.48090371, 0.58903445, 0.51568266])

#array([0.55223149, 0.53365617, 0.34351949, 0.29860724, 0.38930913,
#       0.41088855, 0.50844363, 0.47915567, 0.60451423, 0.50721266])

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
